/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parking_vehiculos;

import java.util.ArrayList;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class Panel_ingresar extends javax.swing.JPanel {
    
    String hora, minuto,Hora_completa;
    public ArrayList<Vehiculos> arr;
  
    /**
     * Creates new form Panel_ingresar
     *
     * @param arr
     */
    public Panel_ingresar(ArrayList<Vehiculos> arr) {
        initComponents();
        this.arr = arr;
    

    }
     public String hora() {
        Calendar calendario = new GregorianCalendar();
        Date horaactual = new Date();
        calendario.setTime(horaactual);
        hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        minuto = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        return Hora_completa=hora+":"+minuto;
    }

    public String fecha() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup_tipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_patenteingresar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_dueñoingresar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbtn_moto = new javax.swing.JRadioButton();
        rbtn_camioneta = new javax.swing.JRadioButton();
        rbtn_auto = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(650, 500));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Ingreso de vehiculos al parking");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("PATENTE");

        txt_patenteingresar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txt_patenteingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_patenteingresarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("DUEÑO");

        txt_dueñoingresar.setFont(new java.awt.Font("Dubai Light", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Tipo de vehiculo");

        btn_registrar.setBackground(new java.awt.Color(51, 0, 0));
        btn_registrar.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        btn_registrar.setText("REGISTRAR");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        btngroup_tipo.add(rbtn_moto);
        rbtn_moto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbtn_moto.setText("Moto");
        rbtn_moto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_motoActionPerformed(evt);
            }
        });

        btngroup_tipo.add(rbtn_camioneta);
        rbtn_camioneta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbtn_camioneta.setText("Camioneta");
        rbtn_camioneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_camionetaActionPerformed(evt);
            }
        });

        btngroup_tipo.add(rbtn_auto);
        rbtn_auto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rbtn_auto.setText("Auto");
        rbtn_auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_autoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_auto)
                .addGap(64, 64, 64)
                .addComponent(rbtn_camioneta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtn_moto)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_camioneta)
                    .addComponent(rbtn_auto)
                    .addComponent(rbtn_moto))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(171, 171, 171)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(135, 135, 135))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(161, 161, 161)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_dueñoingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(txt_patenteingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_patenteingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_dueñoingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_patenteingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_patenteingresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_patenteingresarActionPerformed

    private void rbtn_autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_autoActionPerformed

    }//GEN-LAST:event_rbtn_autoActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        registrar();
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void rbtn_camionetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_camionetaActionPerformed

    }//GEN-LAST:event_rbtn_camionetaActionPerformed

    private void rbtn_motoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_motoActionPerformed

    }//GEN-LAST:event_rbtn_motoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrar;
    private javax.swing.ButtonGroup btngroup_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtn_auto;
    private javax.swing.JRadioButton rbtn_camioneta;
    private javax.swing.JRadioButton rbtn_moto;
    private javax.swing.JTextField txt_dueñoingresar;
    private javax.swing.JTextField txt_patenteingresar;
    // End of variables declaration//GEN-END:variables

    //FUNCION PARA REGISTRAR VEHICULO EN EL PARKING
    public void registrar() {
        String Dueño;
        String Patente;
        String tipo;
        String Fecha;
        String Hora;

        Patente = txt_patenteingresar.getText();
        Dueño = txt_dueñoingresar.getText();
        tipo = tipovehiculo();
        Fecha = fecha();
        Hora= hora();

        arr.add(new Vehiculos(Dueño, Patente, tipo, Fecha, Hora));

        JOptionPane.showMessageDialog(null, "Guardado exitoso!!");
        txt_patenteingresar.setText("");
        txt_dueñoingresar.setText("");
        btngroup_tipo.clearSelection();
    }

    public String tipovehiculo() {
        String tipo;
        tipo = "";

        if (rbtn_auto.isSelected()) {
            tipo = "auto";
        }
        if (rbtn_camioneta.isSelected()) {
            tipo = "camioneta";
        }
        if (rbtn_moto.isSelected()) {
            tipo = "moto";
        }
        return tipo;
    }
}
